name: stalker_gamma_updater
description: A simple command line application for updating Stalker G.A.M.M.A.
version: 0.0.2

platform:
  linux:
  windows:

publish_to: none

executables:
  gamma_updater: bin/cli

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  http: ^0.13.5
  file: ^6.1.4
  get_it: ^7.2.0
  logging: ^1.1.0
  io: ^1.0.3
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  mockito: ^5.3.2
  build_runner: ^2.3.2
