name: stalker_gamma_updater
description: A simple command line application for updating Stalker G.A.M.M.A.
version: 0.0.2

platform:
  linux:
  windows:

publish_to: none

executables:
  gamma_updater: bin/cli

environment:
  sdk: '>=3.0.0 <3.6.0'

dependencies:
  http: ^1.2.2
  file: ^7.0.1
  get_it: ^8.0.2
  logging: ^1.1.0
  io: ^1.0.3
  args: ^2.3.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
  mockito: ^5.3.2
  build_runner: ^2.3.2
