name: Build Stalker GAMMA Updater Binaries
run-name: ${{ github.actor }} has initiated a build ✨
on: [workflow_dispatch]
jobs:
  Cross-compile-and-upload:
    strategy:
      # In the future we may change this to false, so that if one build fails
      # the other will still continue on.
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output-name: stalker_gamma_updater
            artifact-postfix: linux
          - os: windows-latest
            output-name: stalker_gamma_updater.exe
            artifact-postfix: windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
      - run: mkdir build
      - name: Install dependencies
        run: dart pub get
      - name: compile exe
        run: dart compile exe bin/cli.dart -v -o build/${{ matrix.output-name }}
      - name: Tar to maintain casing and permissions
        uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          files: |
            ./build
            ./resources/${{ matrix.artifact-postfix }}
          outPath: stalker-gamma-updater.tar
      - uses: actions/upload-artifact@v3
        with:
          name: stalker-gamma-updater-${{ matrix.artifact-postfix }}
          path: stalker-gamma-updater.tar
          retention-days: 30