name: Build Stalker GAMMA Updater Binaries
run-name: ${{ github.actor }} has initiated a build ✨
on: [workflow_dispatch]
jobs:
  Cross-compile-and-upload:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output-name: stalker_gamma_updater
            artifact-postfix: linux
          - os: windows-latest
            output-name: stalker_gamma_updater.exe
            artifact-postfix: windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
      - run: mkdir build
      - name: Install dependencies
        run: dart pub get
      - name: compile exe
        run: dart compile exe -v -o build/${{ matrix.output-name }}
      - name: Tarball to maintain casing and permissions
        run: tar -cvf stalker-gamma-updater.tar build/ resources/${{ matrix.artifact-postfix }}
      - uses: actions/upload-artifact@v3
        with:
          name: stalker-gamma-updater-${{ matrix.artifact-postfix }}
          path: stalker-gamma-updater.tar
          retention-days: 30